---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: qa-deployment
spec:
  replicas: 1
  revisionHistoryLimit: 1  
  selector:
    matchLabels:
      app: qa-app
  template:
    metadata:
      labels:
        app: qa-app
    spec:
      containers:
      - name: webserver-simple
        imagePullPolicy: Always     
        image: docker.io/kostiscodefresh/smart-rollout:latest           
        env:
          - name: APP_VERSION
            value: "2.0"
          - name: APP_COLOR
            value: "#F1A94E" # Blue 44B3C2 and Yellow F1A94E and purple #c034eb
        ports:
        - containerPort: 8080
        livenessProbe:
          httpGet:
            path: /health/live
            port: 8080
        readinessProbe:
          httpGet:
            path: /health/ready
            port: 8080  