apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: smart-rollouts-demo
spec:
  replicas: 5
  strategy:
    canary:
      canaryService: argo-rollouts-canary-service # our created canary service
      stableService: argo-rollouts-stable-service # our created stable service
      trafficRouting:
        managedRoutes:
        - name: canary-route1
        - name: canary-route2      
        plugins:
          argoproj-labs/gatewayAPI:
            httpRoute: argo-rollouts-http-route # our created httproute
            namespace: default # namespace where this rollout resides
      steps:
        - setWeight: 50
        - setHeaderRoute:
            name: canary-route1
            match:
              - headerName: X-Canary
                headerValue:
                  exact: "yes"         
        - pause: {}
        - setWeight: 100
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: rollouts-demo
  template:
    metadata:
      labels:
        app: rollouts-demo
    spec:
      containers:
        - name: rollouts-demo
          # image: docker.io/kostiscodefresh/traefik-demo-app:main
          # image: kostiscodefresh/summer-of-k8s-app:v1
          # image: kostiscodefresh/smart-rollout:latest          
          # image: kostiscodefresh/summer-of-k8s-app:v2
          image: kostiscodefresh/summer-of-k8s-app:v3           
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /health/live
              port: 8080
          readinessProbe:
            httpGet:
              path: /health/ready
              port: 8080  